<img src='bp_algorithm.png'>

In [68]:
import numpy as np
w_i_h = np.random.rand(3,2)
w_h_o = np.random.rand(2,3)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(x):
    return sigmoid(x) * (1 - sigmoid(x))

lr = 0.1

In [69]:
w_i_h

array([[ 0.44506856,  0.85799088],
       [ 0.89835655,  0.79935786],
       [ 0.16874942,  0.85356893]])

In [70]:
w_h_o

array([[ 0.25919602,  0.26252708,  0.94368872],
       [ 0.89170853,  0.42793014,  0.87620351]])

In [71]:
'''Input'''
x = np.array([1,1],ndmin=2).T

'''target'''

y = np.array([0,1], ndmin=2).T

In [72]:
'''forward propagation'''
hidden_input = np.dot(w_i_h, x)
print(hidden_input)
hidden_output = sigmoid(hidden_input)
print(hidden_output)

print('----------------------------')

final_input = np.dot(w_h_o, hidden_output)
print(final_input)
final_output = sigmoid(final_input)
print(final_output)

[[ 1.30305945]
 [ 1.69771442]
 [ 1.02231835]]
[[ 0.78634943]
 [ 0.84523599]
 [ 0.73542394]]
----------------------------
[[ 1.11972726]
 [ 1.70727749]]
[[ 0.75393812]
 [ 0.84648283]]


<hr>
# Backpropragation

In [73]:
'''Backpropagation!!!'''
'''
Создаем нулевую матрицу, благодаря которой будем изменять веса нейросети
'''
nw_1 = np.zeros(w_i_h.shape)
nw_2 = np.zeros(w_h_o.shape)
print(nw_1, end='\n\n')
print(nw_2)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [74]:
'''
Вычисляем ошибки на нодах всех слоёв кроме первого слоя
'''
# delta_out = final_output - y * sigmoid_deriv(final_output)
delta_out = final_output - y
delta_hidd = np.dot(w_h_o.T, delta_out) * sigmoid_deriv(hidden_input)


In [75]:
print(delta_out, end='\n\n')
print(delta_hidd)

[[ 0.75393812]
 [-0.15351717]]

[[ 0.00983247]
 [ 0.01729788]
 [ 0.11226439]]


In [76]:
fornabla_h_o = np.dot(delta_out, hidden_output.T)
fornabla_h_o

array([[ 0.59285882,  0.63725564,  0.55446415],
       [-0.12071814, -0.12975824, -0.1129002 ]])

In [77]:
fornabla_i_h = np.dot(delta_hidd, x.T)
fornabla_i_h

array([[ 0.00983247,  0.00983247],
       [ 0.01729788,  0.01729788],
       [ 0.11226439,  0.11226439]])

In [78]:
nw_1 = nw_1 + fornabla_i_h
nw_1

array([[ 0.00983247,  0.00983247],
       [ 0.01729788,  0.01729788],
       [ 0.11226439,  0.11226439]])

In [79]:
nw_2 = nw_2 + fornabla_h_o
nw_2

array([[ 0.59285882,  0.63725564,  0.55446415],
       [-0.12071814, -0.12975824, -0.1129002 ]])

<hr>

In [80]:
w_i_h = w_i_h + -lr * nw_1
w_i_h

array([[ 0.44408532,  0.85700763],
       [ 0.89662677,  0.79762808],
       [ 0.15752299,  0.84234249]])

In [81]:
w_h_o = w_h_o + -lr * nw_2
w_h_o

array([[ 0.19991014,  0.19880152,  0.88824231],
       [ 0.90378035,  0.44090596,  0.88749353]])